"""add Department

Revision ID: 87169d7b6aa4
Revises: b86a2157855d
Create Date: 2025-02-28 12:49:37.856919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87169d7b6aa4'
down_revision = 'b86a2157855d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
